Updated README.md with mobile solutions
metakgp/erp-auto-login pull request #29
Opened 2020-09-10 19:55 UTC by sahil-shubham

Added step wise instructions for mobile users to be able to use this extension

2020-09-10 20:17 UTC, thealphadollar requested changes
This is super cool! And I really like how you have gone a step further to add detailed instructions for both browsers. Thanks a lot for the efforts Sahil ❤️

I've suggested two minor changes 😀 Please fix them as your schedule permits.

2020-09-10 20:17 UTC, thealphadollar commented on README.md
> +  1. Dowload Yandex Browser from Play Store
Nitpicking: spelling of download

2020-09-10 20:17 UTC, thealphadollar commented on README.md
> +  1. Dowload Kiwi Browser from Play Store
Nitpicking: spelling of download

2020-09-10 20:21 UTC, sahil-shubham commented on README.md
> +  1. Dowload Kiwi Browser from Play Store
done, thank you.

2020-09-10 20:23 UTC, sahil-shubham commented
Should I also add screenshots for few of the steps?

2020-09-10 20:42 UTC, thealphadollar commented
Yeah, that would be fabulous if it doesn't take much of your time.

On Fri, 11 Sep, 2020, 1:53 am Sahil Shubham, <notifications@github.com>
wrote:

> Should I also add screenshots for few of the steps?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/metakgp/erp-auto-login/pull/29#issuecomment-690705838>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH2K2IBPF5NU3N27LU2MYNTSFEYURANCNFSM4RFYBYWQ>
> .
>

2020-09-11 05:42 UTC, thealphadollar requested changes
This is super cool - I liked how you have emphasized the important part of the image by marking it... that is ingenious!

There are three trivial spelling issues, I've added suggestions for fixing them :rocket:

2020-09-11 05:42 UTC, thealphadollar commented on README.md
> +    [yandex-extensions](instruction_imgaes/yandex_extensions.jpg)
```suggestion
    [yandex-extensions](instruction_images/yandex_extensions.jpg)
```

2020-09-11 05:42 UTC, thealphadollar commented on README.md
> +    [yandex-desktop-version](instruction_imgaes/yandex_desktop.jpg)
```suggestion
    [yandex-desktop-version](instruction_images/yandex_desktop.jpg)
```

2020-09-11 05:42 UTC, thealphadollar commented on README.md
> +    [kiwi-extensions](instruction_imgaes/kiwi_extensions.jpg)
```suggestion
    [kiwi-extensions](instruction_images/kiwi_extensions.jpg)
```

2020-09-11 05:53 UTC, sahil-shubham commented
@thealphadollar Thank you, I started fixing these right when I pushed the commit. I would have to decrease the amount of spelling mistakes I make :sweat_smile: 

I decreased the width of the images as they looked really big. Plus, I also added a link to CONTRIBUTING.md, it has nothing to do with this issue but it makes the README better.

2020-09-11 06:11 UTC, thealphadollar approved these changes
This looks amazing to me, and ready to ship! Thanks a lot Sahil for the amazing contributions, and going one step extra, I didn't expect anything less :star2:

2020-09-11 06:11 UTC, merged