[WIP] Migrating to manifest v3
metakgp/erp-auto-login pull request #53
Opened 2022-04-18 15:51 UTC by rajivharlalka

- Updated the manifest to Version 3
- Removed unused scripts that caused import error.

2022-04-18 15:54 UTC, rajivharlalka commented
Was getting an error in a script (skip-form.js) and neither was able to get which popup it asks for. 
![image](https://user-images.githubusercontent.com/68731551/163835264-900272dd-179c-4605-a83d-ab3a55795b02.png).

This is the only error left to be resolved in the migration.

2022-04-18 16:43 UTC, thealphadollar commented
The popup has been removed from ERP, now. Please remove the script and its usage.

Thanks for the work on the migration.

2022-04-19 07:47 UTC, thealphadollar requested changes
Thanks, almost there.

2022-04-19 07:47 UTC, thealphadollar commented on skip-form.js
> +// Pop Up removed from erp , commented for future Reference and Use
Do not leave a comment, and remove the code altogether. We will have the code in GitHub history for future reference.

2022-04-19 08:13 UTC, thealphadollar approved these changes

2022-04-19 08:13 UTC, merged